version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - ${IP}:${PORT}:80
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - ${IP}:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASS: "${DB_PASSWORD}"
    volumes:
      - ./db-data:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      UPLOAD_LIMIT: 50M
    depends_on:
      - db
    ports:
      - ${IP}:${PHPMYADMIN_PORT}:80
    links:
      - db:db